image: registry.redhat.io/rhel9/nodejs-20:latest
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - mv content/.vitepress/dist public
  artifacts:
    paths:
      - public
  only:
    - main
